services:
  doc2embed:
    image: bill73777/doc2embed:latest
    container_name: doc2embed
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
